// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Helpers;

namespace SMS.Migrations.MysqlData
{
    [DbContext(typeof(MysqlDataContext))]
    [Migration("20211102041944_tripdetailsv3")]
    partial class tripdetailsv3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("DependentsStudent", b =>
                {
                    b.Property<int>("DependentsdetailsDependentsId")
                        .HasColumnType("int");

                    b.Property<int>("StudentsStudentId")
                        .HasColumnType("int");

                    b.HasKey("DependentsdetailsDependentsId", "StudentsStudentId");

                    b.HasIndex("StudentsStudentId");

                    b.ToTable("DependentsStudent");
                });

            modelBuilder.Entity("SMS.Models.Academics.LessonPlan", b =>
                {
                    b.Property<int>("LessonPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AcademicClassId")
                        .HasColumnType("int");

                    b.Property<int>("AcademicClassSubjectId")
                        .HasColumnType("int");

                    b.Property<string>("LessonPlanCheckDigi")
                        .HasColumnType("text");

                    b.Property<string>("activity")
                        .HasColumnType("text");

                    b.Property<string>("classActivity")
                        .HasColumnType("text");

                    b.Property<string>("classWork")
                        .HasColumnType("text");

                    b.Property<string>("concept")
                        .HasColumnType("text");

                    b.Property<DateTime?>("date")
                        .HasColumnType("datetime");

                    b.Property<string>("extraInfo")
                        .HasColumnType("text");

                    b.Property<string>("games")
                        .HasColumnType("text");

                    b.Property<string>("homeWork")
                        .HasColumnType("text");

                    b.Property<string>("lesson")
                        .HasColumnType("text");

                    b.Property<string>("topic")
                        .HasColumnType("text");

                    b.HasKey("LessonPlanId");

                    b.ToTable("LessonPlans");
                });

            modelBuilder.Entity("SMS.Models.Attendance.StaffAttendance", b =>
                {
                    b.Property<int>("StaffAttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Absent")
                        .HasColumnType("int");

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("datetime");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("text");

                    b.Property<int>("HalfDay")
                        .HasColumnType("int");

                    b.Property<int>("Present")
                        .HasColumnType("int");

                    b.Property<int>("RowInactive")
                        .HasColumnType("int");

                    b.Property<string>("StaffName")
                        .HasColumnType("text");

                    b.Property<int>("StaffTypeId")
                        .HasColumnType("int");

                    b.HasKey("StaffAttendanceId");

                    b.ToTable("StaffAttendances");
                });

            modelBuilder.Entity("SMS.Models.Attendance.StudentAttendance", b =>
                {
                    b.Property<int>("StudentAttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Absent")
                        .HasColumnType("int");

                    b.Property<int>("AdmissionNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Class")
                        .HasColumnType("text");

                    b.Property<int>("HalfDay")
                        .HasColumnType("int");

                    b.Property<int>("Present")
                        .HasColumnType("int");

                    b.Property<int>("RowInactive")
                        .HasColumnType("int");

                    b.Property<string>("Section")
                        .HasColumnType("text");

                    b.Property<string>("StudentName")
                        .HasColumnType("text");

                    b.HasKey("StudentAttendanceId");

                    b.ToTable("StudentAttendances");
                });

            modelBuilder.Entity("SMS.Models.Bank", b =>
                {
                    b.Property<int>("BankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BankDescr")
                        .HasColumnType("text");

                    b.HasKey("BankId");

                    b.ToTable("Banks");

                    b.HasData(
                        new
                        {
                            BankId = 1,
                            BankDescr = "State Bank of India (SBI)"
                        },
                        new
                        {
                            BankId = 2,
                            BankDescr = "Punjab National Bank"
                        },
                        new
                        {
                            BankId = 3,
                            BankDescr = "Bank of Baroda (With Merger of Dena Bank & Vijaya Bank)"
                        },
                        new
                        {
                            BankId = 4,
                            BankDescr = "Canara Bank (With Merger of Syndicate Bank)"
                        },
                        new
                        {
                            BankId = 5,
                            BankDescr = "Union Bank of India (With Merger of Andhra Bank and Corporation Bank)"
                        },
                        new
                        {
                            BankId = 6,
                            BankDescr = "Indian Bank (With Merger of Allahabad Bank)"
                        },
                        new
                        {
                            BankId = 7,
                            BankDescr = "Central Bank of India"
                        },
                        new
                        {
                            BankId = 8,
                            BankDescr = "UCO Bank"
                        },
                        new
                        {
                            BankId = 9,
                            BankDescr = "Bank of Maharashtra"
                        },
                        new
                        {
                            BankId = 10,
                            BankDescr = "Punjab & Sindh Bank"
                        },
                        new
                        {
                            BankId = 11,
                            BankDescr = "Bandhan Bank"
                        },
                        new
                        {
                            BankId = 12,
                            BankDescr = "Catholic Syrian Bank"
                        },
                        new
                        {
                            BankId = 13,
                            BankDescr = "City Union Bank"
                        },
                        new
                        {
                            BankId = 14,
                            BankDescr = "DCB Bank"
                        },
                        new
                        {
                            BankId = 15,
                            BankDescr = "Dhanlaxmi Bank"
                        },
                        new
                        {
                            BankId = 16,
                            BankDescr = "Federal Bank"
                        },
                        new
                        {
                            BankId = 17,
                            BankDescr = "HDFC Bank"
                        },
                        new
                        {
                            BankId = 18,
                            BankDescr = "ICICI Bank"
                        },
                        new
                        {
                            BankId = 19,
                            BankDescr = "IDBI Bank"
                        },
                        new
                        {
                            BankId = 20,
                            BankDescr = "IDFC First Bank"
                        },
                        new
                        {
                            BankId = 21,
                            BankDescr = "Jammu & Kashmir Bank"
                        },
                        new
                        {
                            BankId = 22,
                            BankDescr = "Karur Vysya Bank"
                        },
                        new
                        {
                            BankId = 23,
                            BankDescr = "Lakshmi Vilas Bank"
                        },
                        new
                        {
                            BankId = 24,
                            BankDescr = "Nainital Bank"
                        },
                        new
                        {
                            BankId = 25,
                            BankDescr = "RBL Bank"
                        },
                        new
                        {
                            BankId = 26,
                            BankDescr = "South Indian Bank"
                        },
                        new
                        {
                            BankId = 27,
                            BankDescr = "Tamilnad Mercantile Bank Limited"
                        },
                        new
                        {
                            BankId = 28,
                            BankDescr = "Axis Bank"
                        },
                        new
                        {
                            BankId = 29,
                            BankDescr = "Kotak Mahindra Bank"
                        },
                        new
                        {
                            BankId = 30,
                            BankDescr = "Bank of India"
                        },
                        new
                        {
                            BankId = 31,
                            BankDescr = "Canara Bank"
                        },
                        new
                        {
                            BankId = 32,
                            BankDescr = "IndusInd Bank"
                        },
                        new
                        {
                            BankId = 33,
                            BankDescr = "YES Bank"
                        },
                        new
                        {
                            BankId = 34,
                            BankDescr = "Karnataka Bank"
                        },
                        new
                        {
                            BankId = 35,
                            BankDescr = "Indian Overseas Bank"
                        },
                        new
                        {
                            BankId = 36,
                            BankDescr = "Union Bank of India (Andhra Bank & Corporation Bank)"
                        });
                });

            modelBuilder.Entity("SMS.Models.Bloodgroup", b =>
                {
                    b.Property<int>("BloodgroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BloodgroupName")
                        .HasColumnType("text");

                    b.HasKey("BloodgroupId");

                    b.ToTable("Bloodgroups");

                    b.HasData(
                        new
                        {
                            BloodgroupId = 1,
                            BloodgroupName = "(A +)"
                        },
                        new
                        {
                            BloodgroupId = 2,
                            BloodgroupName = "(A -)"
                        },
                        new
                        {
                            BloodgroupId = 3,
                            BloodgroupName = "(B +)"
                        },
                        new
                        {
                            BloodgroupId = 4,
                            BloodgroupName = "(B -)"
                        },
                        new
                        {
                            BloodgroupId = 5,
                            BloodgroupName = "(O +)"
                        },
                        new
                        {
                            BloodgroupId = 6,
                            BloodgroupName = "(O -)"
                        },
                        new
                        {
                            BloodgroupId = 7,
                            BloodgroupName = "(AB +)"
                        },
                        new
                        {
                            BloodgroupId = 8,
                            BloodgroupName = "(AB -)"
                        });
                });

            modelBuilder.Entity("SMS.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("cityDescr")
                        .HasColumnType("text");

                    b.HasKey("CityId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            cityDescr = "Chennai"
                        },
                        new
                        {
                            CityId = 2,
                            cityDescr = "Coimbatore"
                        },
                        new
                        {
                            CityId = 3,
                            cityDescr = "Madurai"
                        },
                        new
                        {
                            CityId = 4,
                            cityDescr = "Tiruchirappa"
                        },
                        new
                        {
                            CityId = 5,
                            cityDescr = "Salem"
                        },
                        new
                        {
                            CityId = 6,
                            cityDescr = "Tirunelveli"
                        },
                        new
                        {
                            CityId = 7,
                            cityDescr = "Tiruppur"
                        },
                        new
                        {
                            CityId = 8,
                            cityDescr = "Vellore"
                        },
                        new
                        {
                            CityId = 9,
                            cityDescr = "Erode"
                        },
                        new
                        {
                            CityId = 10,
                            cityDescr = "Thoothukkudi"
                        },
                        new
                        {
                            CityId = 11,
                            cityDescr = "Dindigul"
                        },
                        new
                        {
                            CityId = 12,
                            cityDescr = "Thanjavur"
                        },
                        new
                        {
                            CityId = 13,
                            cityDescr = "Ranipet"
                        },
                        new
                        {
                            CityId = 14,
                            cityDescr = "Sivakasi"
                        },
                        new
                        {
                            CityId = 15,
                            cityDescr = "Karur"
                        },
                        new
                        {
                            CityId = 16,
                            cityDescr = "Udhagamandal"
                        },
                        new
                        {
                            CityId = 17,
                            cityDescr = "Hosur"
                        },
                        new
                        {
                            CityId = 18,
                            cityDescr = "Nagercoil"
                        },
                        new
                        {
                            CityId = 19,
                            cityDescr = "Kanchipuram"
                        },
                        new
                        {
                            CityId = 20,
                            cityDescr = "Kumarapalaya"
                        },
                        new
                        {
                            CityId = 21,
                            cityDescr = "Karaikkudi"
                        },
                        new
                        {
                            CityId = 22,
                            cityDescr = "Neyveli"
                        },
                        new
                        {
                            CityId = 23,
                            cityDescr = "Cuddalore"
                        },
                        new
                        {
                            CityId = 24,
                            cityDescr = "Kumbakonam"
                        },
                        new
                        {
                            CityId = 25,
                            cityDescr = "Tiruvannamal"
                        },
                        new
                        {
                            CityId = 26,
                            cityDescr = "Pollachi"
                        },
                        new
                        {
                            CityId = 27,
                            cityDescr = "Rajapalayam"
                        },
                        new
                        {
                            CityId = 28,
                            cityDescr = "Gudiyatham"
                        },
                        new
                        {
                            CityId = 29,
                            cityDescr = "Pudukkottai"
                        },
                        new
                        {
                            CityId = 30,
                            cityDescr = "Vaniyambadi"
                        },
                        new
                        {
                            CityId = 31,
                            cityDescr = "Ambur"
                        });
                });

            modelBuilder.Entity("SMS.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("countryDescr")
                        .HasColumnType("text");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("SMS.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("text");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            DepartmentName = "Admin"
                        },
                        new
                        {
                            DepartmentId = 2,
                            DepartmentName = "Finance"
                        },
                        new
                        {
                            DepartmentId = 3,
                            DepartmentName = "Library"
                        },
                        new
                        {
                            DepartmentId = 4,
                            DepartmentName = "IT"
                        },
                        new
                        {
                            DepartmentId = 5,
                            DepartmentName = "Non Teaching"
                        },
                        new
                        {
                            DepartmentId = 6,
                            DepartmentName = "English"
                        },
                        new
                        {
                            DepartmentId = 7,
                            DepartmentName = "Tamil"
                        },
                        new
                        {
                            DepartmentId = 8,
                            DepartmentName = "Maths"
                        },
                        new
                        {
                            DepartmentId = 9,
                            DepartmentName = "Science"
                        },
                        new
                        {
                            DepartmentId = 10,
                            DepartmentName = "Social Studies"
                        },
                        new
                        {
                            DepartmentId = 11,
                            DepartmentName = "Hindi"
                        },
                        new
                        {
                            DepartmentId = 12,
                            DepartmentName = "Commerce"
                        },
                        new
                        {
                            DepartmentId = 13,
                            DepartmentName = "Economics"
                        },
                        new
                        {
                            DepartmentId = 14,
                            DepartmentName = "Accounts"
                        },
                        new
                        {
                            DepartmentId = 15,
                            DepartmentName = "PET"
                        });
                });

            modelBuilder.Entity("SMS.Models.Dependents", b =>
                {
                    b.Property<int>("DependentsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AadharNumber")
                        .HasColumnType("text");

                    b.Property<long>("AnnualIncome")
                        .HasColumnType("bigint");

                    b.Property<bool>("BvEmployee")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Company")
                        .HasColumnType("text");

                    b.Property<string>("Designation")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<long>("MobileNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("Occupation")
                        .HasColumnType("text");

                    b.Property<int>("SalutationId")
                        .HasColumnType("int");

                    b.HasKey("DependentsId");

                    b.ToTable("Dependents");
                });

            modelBuilder.Entity("SMS.Models.Designation", b =>
                {
                    b.Property<int>("DesignationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DesignationName")
                        .HasColumnType("text");

                    b.HasKey("DesignationId");

                    b.ToTable("Designations");

                    b.HasData(
                        new
                        {
                            DesignationId = 1,
                            DesignationName = "Teacher"
                        },
                        new
                        {
                            DesignationId = 2,
                            DesignationName = "Co-ordinator"
                        },
                        new
                        {
                            DesignationId = 3,
                            DesignationName = "HOD"
                        },
                        new
                        {
                            DesignationId = 4,
                            DesignationName = "Non-Teaching"
                        },
                        new
                        {
                            DesignationId = 5,
                            DesignationName = "Office Associate"
                        },
                        new
                        {
                            DesignationId = 6,
                            DesignationName = "Finance Associate"
                        },
                        new
                        {
                            DesignationId = 7,
                            DesignationName = "Principal"
                        },
                        new
                        {
                            DesignationId = 8,
                            DesignationName = "Librarian"
                        },
                        new
                        {
                            DesignationId = 9,
                            DesignationName = "Vice Principal"
                        });
                });

            modelBuilder.Entity("SMS.Models.Education", b =>
                {
                    b.Property<int>("EducationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("eduDescr")
                        .HasColumnType("text");

                    b.HasKey("EducationId");

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("SMS.Models.EmployeementStatus", b =>
                {
                    b.Property<int>("EmployeementStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasKey("EmployeementStatusId");

                    b.ToTable("EmployeementStatuses");

                    b.HasData(
                        new
                        {
                            EmployeementStatusId = 1,
                            Description = "Active"
                        },
                        new
                        {
                            EmployeementStatusId = 2,
                            Description = "In active"
                        },
                        new
                        {
                            EmployeementStatusId = 3,
                            Description = "Terminated"
                        },
                        new
                        {
                            EmployeementStatusId = 4,
                            Description = "In Leave"
                        });
                });

            modelBuilder.Entity("SMS.Models.Gender", b =>
                {
                    b.Property<int>("GenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("GenderName")
                        .HasColumnType("text");

                    b.HasKey("GenderId");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            GenderId = 1,
                            GenderName = "Male"
                        },
                        new
                        {
                            GenderId = 2,
                            GenderName = "Female"
                        },
                        new
                        {
                            GenderId = 3,
                            GenderName = "Trans"
                        },
                        new
                        {
                            GenderId = 4,
                            GenderName = "Not willing to disclose"
                        });
                });

            modelBuilder.Entity("SMS.Models.Inventory.Inventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<byte>("BillCopy")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<int>("InventoryItemTypeId")
                        .HasColumnType("int");

                    b.Property<int>("InventoryItemUsageAreaId")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .HasColumnType("text");

                    b.Property<string>("ModelNumber")
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text");

                    b.Property<string>("VendorAddress")
                        .HasColumnType("text");

                    b.Property<string>("VendorName")
                        .HasColumnType("text");

                    b.Property<string>("VendorNumber")
                        .HasColumnType("text");

                    b.Property<bool>("WarrenOrGarantee")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("WarrenOrGarenInfo")
                        .HasColumnType("text");

                    b.HasKey("InventoryId");

                    b.HasIndex("InventoryItemTypeId");

                    b.HasIndex("InventoryItemUsageAreaId");

                    b.ToTable("Inventorys");
                });

            modelBuilder.Entity("SMS.Models.Inventory.InventoryDefect", b =>
                {
                    b.Property<int>("InventoryDefectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DefectDesc")
                        .HasColumnType("text");

                    b.Property<string>("ItemCode")
                        .HasColumnType("text");

                    b.Property<string>("ItemName")
                        .HasColumnType("text");

                    b.HasKey("InventoryDefectId");

                    b.ToTable("InventoryDefects");
                });

            modelBuilder.Entity("SMS.Models.Inventory.InventoryItemType", b =>
                {
                    b.Property<int>("InventoryItemTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasKey("InventoryItemTypeId");

                    b.ToTable("InventoryItemTypes");

                    b.HasData(
                        new
                        {
                            InventoryItemTypeId = 1,
                            Description = "Stationery"
                        },
                        new
                        {
                            InventoryItemTypeId = 2,
                            Description = "Chair"
                        },
                        new
                        {
                            InventoryItemTypeId = 3,
                            Description = "Bench"
                        },
                        new
                        {
                            InventoryItemTypeId = 4,
                            Description = "Plumbing Tools"
                        },
                        new
                        {
                            InventoryItemTypeId = 5,
                            Description = "Light"
                        },
                        new
                        {
                            InventoryItemTypeId = 6,
                            Description = "Gadgets"
                        },
                        new
                        {
                            InventoryItemTypeId = 7,
                            Description = "Fan"
                        },
                        new
                        {
                            InventoryItemTypeId = 8,
                            Description = "Board"
                        },
                        new
                        {
                            InventoryItemTypeId = 9,
                            Description = "Medicines"
                        },
                        new
                        {
                            InventoryItemTypeId = 10,
                            Description = "Printer"
                        },
                        new
                        {
                            InventoryItemTypeId = 11,
                            Description = "Computer"
                        },
                        new
                        {
                            InventoryItemTypeId = 12,
                            Description = "Laptops"
                        },
                        new
                        {
                            InventoryItemTypeId = 13,
                            Description = "IT Accesories"
                        },
                        new
                        {
                            InventoryItemTypeId = 14,
                            Description = "Office items"
                        },
                        new
                        {
                            InventoryItemTypeId = 15,
                            Description = "Paper"
                        },
                        new
                        {
                            InventoryItemTypeId = 16,
                            Description = "Xerox Machine"
                        },
                        new
                        {
                            InventoryItemTypeId = 17,
                            Description = "Bathroom Items"
                        },
                        new
                        {
                            InventoryItemTypeId = 18,
                            Description = "Projector"
                        },
                        new
                        {
                            InventoryItemTypeId = 19,
                            Description = "Lab Chemicals"
                        },
                        new
                        {
                            InventoryItemTypeId = 20,
                            Description = "Laboratory Product"
                        },
                        new
                        {
                            InventoryItemTypeId = 21,
                            Description = "Specimen"
                        },
                        new
                        {
                            InventoryItemTypeId = 22,
                            Description = "Paint"
                        },
                        new
                        {
                            InventoryItemTypeId = 23,
                            Description = "Hardwares"
                        },
                        new
                        {
                            InventoryItemTypeId = 24,
                            Description = "Kitchen Utensils"
                        },
                        new
                        {
                            InventoryItemTypeId = 25,
                            Description = "Generator"
                        },
                        new
                        {
                            InventoryItemTypeId = 26,
                            Description = "AC"
                        },
                        new
                        {
                            InventoryItemTypeId = 27,
                            Description = "Water Doctor"
                        },
                        new
                        {
                            InventoryItemTypeId = 28,
                            Description = "Celebration Kit"
                        },
                        new
                        {
                            InventoryItemTypeId = 29,
                            Description = "Room Screen"
                        },
                        new
                        {
                            InventoryItemTypeId = 30,
                            Description = "Sports Kit"
                        },
                        new
                        {
                            InventoryItemTypeId = 31,
                            Description = "Swimming pool Kit"
                        });
                });

            modelBuilder.Entity("SMS.Models.Inventory.InventoryItemUsageArea", b =>
                {
                    b.Property<int>("InventoryItemUsageAreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasKey("InventoryItemUsageAreaId");

                    b.ToTable("InventoryItemUsageAreas");

                    b.HasData(
                        new
                        {
                            InventoryItemUsageAreaId = 1,
                            Description = "Lab"
                        },
                        new
                        {
                            InventoryItemUsageAreaId = 2,
                            Description = "Office"
                        },
                        new
                        {
                            InventoryItemUsageAreaId = 3,
                            Description = "Class"
                        },
                        new
                        {
                            InventoryItemUsageAreaId = 4,
                            Description = "General"
                        },
                        new
                        {
                            InventoryItemUsageAreaId = 5,
                            Description = "Bathroom"
                        },
                        new
                        {
                            InventoryItemUsageAreaId = 6,
                            Description = "Sports room"
                        },
                        new
                        {
                            InventoryItemUsageAreaId = 7,
                            Description = "Swimming pool"
                        },
                        new
                        {
                            InventoryItemUsageAreaId = 8,
                            Description = "Play area"
                        },
                        new
                        {
                            InventoryItemUsageAreaId = 9,
                            Description = "Server room"
                        },
                        new
                        {
                            InventoryItemUsageAreaId = 10,
                            Description = "Hall"
                        },
                        new
                        {
                            InventoryItemUsageAreaId = 11,
                            Description = "Veranda"
                        },
                        new
                        {
                            InventoryItemUsageAreaId = 12,
                            Description = "Common area"
                        });
                });

            modelBuilder.Entity("SMS.Models.Language", b =>
                {
                    b.Property<int>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("LanguageDescription")
                        .HasColumnType("text");

                    b.HasKey("LanguageId");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            LanguageId = 1,
                            LanguageDescription = "Hindi"
                        },
                        new
                        {
                            LanguageId = 2,
                            LanguageDescription = "English"
                        },
                        new
                        {
                            LanguageId = 3,
                            LanguageDescription = "Bengali"
                        },
                        new
                        {
                            LanguageId = 4,
                            LanguageDescription = "Marathi"
                        },
                        new
                        {
                            LanguageId = 5,
                            LanguageDescription = "Telugu"
                        },
                        new
                        {
                            LanguageId = 6,
                            LanguageDescription = "Tamil"
                        },
                        new
                        {
                            LanguageId = 7,
                            LanguageDescription = "Gujarati"
                        },
                        new
                        {
                            LanguageId = 8,
                            LanguageDescription = "Urdu"
                        },
                        new
                        {
                            LanguageId = 9,
                            LanguageDescription = "Kannada"
                        },
                        new
                        {
                            LanguageId = 10,
                            LanguageDescription = "Odia"
                        },
                        new
                        {
                            LanguageId = 11,
                            LanguageDescription = "Malayalam"
                        },
                        new
                        {
                            LanguageId = 12,
                            LanguageDescription = "Punjabi"
                        },
                        new
                        {
                            LanguageId = 13,
                            LanguageDescription = "Assamese"
                        },
                        new
                        {
                            LanguageId = 14,
                            LanguageDescription = "French"
                        },
                        new
                        {
                            LanguageId = 15,
                            LanguageDescription = "Others"
                        });
                });

            modelBuilder.Entity("SMS.Models.Leave.StaffLeave", b =>
                {
                    b.Property<int>("StaffLeaveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("LeaveType")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<int?>("StaffId")
                        .HasColumnType("int");

                    b.Property<DateTime>("datefrom")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("dateto")
                        .HasColumnType("datetime");

                    b.Property<string>("leavesession")
                        .HasColumnType("text");

                    b.HasKey("StaffLeaveId");

                    b.HasIndex("StaffId");

                    b.ToTable("StaffLeaves");
                });

            modelBuilder.Entity("SMS.Models.Leave.StudentLeave", b =>
                {
                    b.Property<int>("StudentLeaveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("LeaveType")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("datefrom")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("dateto")
                        .HasColumnType("datetime");

                    b.Property<string>("leavesession")
                        .HasColumnType("text");

                    b.HasKey("StudentLeaveId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentLeaves");
                });

            modelBuilder.Entity("SMS.Models.MaritalStatus", b =>
                {
                    b.Property<int>("MaritalStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("MaritalStatusName")
                        .HasColumnType("text");

                    b.HasKey("MaritalStatusId");

                    b.ToTable("Maritalstatus");

                    b.HasData(
                        new
                        {
                            MaritalStatusId = 1,
                            MaritalStatusName = "Married"
                        },
                        new
                        {
                            MaritalStatusId = 2,
                            MaritalStatusName = "Widowed"
                        },
                        new
                        {
                            MaritalStatusId = 3,
                            MaritalStatusName = "Separated"
                        },
                        new
                        {
                            MaritalStatusId = 4,
                            MaritalStatusName = "Divorced"
                        },
                        new
                        {
                            MaritalStatusId = 5,
                            MaritalStatusName = "Single"
                        });
                });

            modelBuilder.Entity("SMS.Models.Message.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedDate")
                        .HasColumnType("int");

                    b.Property<DateTime>("Expirydate")
                        .HasColumnType("datetime");

                    b.Property<int>("IsReminder")
                        .HasColumnType("int");

                    b.Property<string>("MessageBody")
                        .HasColumnType("text");

                    b.Property<int?>("MessageRecipientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NextReminderDate")
                        .HasColumnType("datetime");

                    b.Property<int>("ParentMessageId")
                        .HasColumnType("int");

                    b.Property<int?>("ReminderFrequencyId")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .HasColumnType("text");

                    b.HasKey("MessageId");

                    b.HasIndex("AccountId");

                    b.HasIndex("MessageRecipientId");

                    b.HasIndex("ParentMessageId");

                    b.HasIndex("ReminderFrequencyId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("SMS.Models.Message.MessageRecipient", b =>
                {
                    b.Property<int>("MessageRecipientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("IsRead")
                        .HasColumnType("int");

                    b.HasKey("MessageRecipientId");

                    b.HasIndex("AccountId");

                    b.ToTable("MessageRecipients");
                });

            modelBuilder.Entity("SMS.Models.Message.ReminderFrequency", b =>
                {
                    b.Property<int>("ReminderFrequencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.Property<char>("IsActive")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("ReminderFrequencyId");

                    b.ToTable("ReminderFrequencies");
                });

            modelBuilder.Entity("SMS.Models.Nationality", b =>
                {
                    b.Property<int>("NationalityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NationalityName")
                        .HasColumnType("text");

                    b.HasKey("NationalityId");

                    b.ToTable("Nationalities");

                    b.HasData(
                        new
                        {
                            NationalityId = 1,
                            NationalityName = "Indian"
                        },
                        new
                        {
                            NationalityId = 2,
                            NationalityName = "Others"
                        },
                        new
                        {
                            NationalityId = 3,
                            NationalityName = "Not willing to disclose"
                        });
                });

            modelBuilder.Entity("SMS.Models.Religion", b =>
                {
                    b.Property<int>("ReligionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ReligionName")
                        .HasColumnType("text");

                    b.HasKey("ReligionId");

                    b.ToTable("Religions");

                    b.HasData(
                        new
                        {
                            ReligionId = 1,
                            ReligionName = "Hindu"
                        },
                        new
                        {
                            ReligionId = 2,
                            ReligionName = "Christian"
                        },
                        new
                        {
                            ReligionId = 3,
                            ReligionName = "Muslim"
                        },
                        new
                        {
                            ReligionId = 4,
                            ReligionName = "Sikh"
                        },
                        new
                        {
                            ReligionId = 5,
                            ReligionName = "Buddhist"
                        },
                        new
                        {
                            ReligionId = 6,
                            ReligionName = "Jains"
                        },
                        new
                        {
                            ReligionId = 7,
                            ReligionName = "Others"
                        },
                        new
                        {
                            ReligionId = 8,
                            ReligionName = "Not willing to disclose"
                        });
                });

            modelBuilder.Entity("SMS.Models.ReportingTo", b =>
                {
                    b.Property<int>("ReportingToId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ReportingDescr")
                        .HasColumnType("text");

                    b.HasKey("ReportingToId");

                    b.ToTable("ReportingTos");
                });

            modelBuilder.Entity("SMS.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Description = "Super Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            Description = "Admin"
                        },
                        new
                        {
                            RoleId = 3,
                            Description = "Finance Admin"
                        },
                        new
                        {
                            RoleId = 4,
                            Description = "Student"
                        },
                        new
                        {
                            RoleId = 5,
                            Description = "Teacher"
                        },
                        new
                        {
                            RoleId = 6,
                            Description = "Inventory Admin"
                        },
                        new
                        {
                            RoleId = 7,
                            Description = "Library Admin"
                        });
                });

            modelBuilder.Entity("SMS.Models.Salutation", b =>
                {
                    b.Property<int>("SalutationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("SalutationName")
                        .HasColumnType("text");

                    b.HasKey("SalutationId");

                    b.ToTable("Salutations");

                    b.HasData(
                        new
                        {
                            SalutationId = 1,
                            SalutationName = "Mr."
                        },
                        new
                        {
                            SalutationId = 2,
                            SalutationName = "Mrs."
                        },
                        new
                        {
                            SalutationId = 3,
                            SalutationName = "Miss"
                        },
                        new
                        {
                            SalutationId = 4,
                            SalutationName = "Master"
                        });
                });

            modelBuilder.Entity("SMS.Models.SchoolName", b =>
                {
                    b.Property<int>("SchoolNameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("SchoolDescr")
                        .HasColumnType("text");

                    b.HasKey("SchoolNameId");

                    b.ToTable("SchoolNames");
                });

            modelBuilder.Entity("SMS.Models.Setup.AcademicClass", b =>
                {
                    b.Property<int>("AcademicClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AcademicClassSubjectId")
                        .HasColumnType("text");

                    b.Property<DateTime>("AcademicYear")
                        .HasColumnType("datetime");

                    b.Property<string>("ClassName")
                        .HasColumnType("text");

                    b.Property<string>("Group")
                        .HasColumnType("text");

                    b.Property<string>("Section")
                        .HasColumnType("text");

                    b.HasKey("AcademicClassId");

                    b.ToTable("AcademicClasses");
                });

            modelBuilder.Entity("SMS.Models.Setup.AcademicClassSubject", b =>
                {
                    b.Property<int>("AcademicClassSubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AcademicClassId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.HasKey("AcademicClassSubjectId");

                    b.ToTable("AcademicClassSubjects");
                });

            modelBuilder.Entity("SMS.Models.Setup.Subject", b =>
                {
                    b.Property<int>("SubjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("SubjectDescr")
                        .HasColumnType("text");

                    b.HasKey("SubjectID");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("SMS.Models.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<string>("AadharNumber")
                        .HasColumnType("text");

                    b.Property<int>("ActiveId")
                        .HasColumnType("int");

                    b.Property<long>("BankAccountNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("BankBranch")
                        .HasColumnType("text");

                    b.Property<string>("BankIfscCode")
                        .HasColumnType("text");

                    b.Property<int>("BankName")
                        .HasColumnType("int");

                    b.Property<int>("BloodGroup")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("DesignationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime");

                    b.Property<int>("EducationId")
                        .HasColumnType("int");

                    b.Property<string>("EmailId")
                        .HasColumnType("text");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("text");

                    b.Property<int>("EmployeementStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Epfnumber")
                        .HasColumnType("text");

                    b.Property<string>("Esinumber")
                        .HasColumnType("text");

                    b.Property<string>("FatherMobileNumber")
                        .HasColumnType("text");

                    b.Property<string>("FatherName")
                        .HasColumnType("text");

                    b.Property<string>("FatherOccupation")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("datetime");

                    b.Property<int>("LanguagesId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<int>("Marritalsatus")
                        .HasColumnType("int");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<long>("Mobile")
                        .HasColumnType("bigint");

                    b.Property<string>("MotherMobileNumber")
                        .HasColumnType("text");

                    b.Property<string>("MotherName")
                        .HasColumnType("text");

                    b.Property<string>("MotherOccupation")
                        .HasColumnType("text");

                    b.Property<int>("MotherTongue")
                        .HasColumnType("int");

                    b.Property<int>("NationalityId")
                        .HasColumnType("int");

                    b.Property<string>("OfficialEmailId")
                        .HasColumnType("text");

                    b.Property<string>("PanNumber")
                        .HasColumnType("text");

                    b.Property<int>("ReligionId")
                        .HasColumnType("int");

                    b.Property<int>("ReportingTo")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("SalutationId")
                        .HasColumnType("int");

                    b.Property<string>("SpouseMobileNumber")
                        .HasColumnType("text");

                    b.Property<string>("SpouseName")
                        .HasColumnType("text");

                    b.Property<string>("SpouseOccupation")
                        .HasColumnType("text");

                    b.Property<int>("StaffAddressId")
                        .HasColumnType("int");

                    b.Property<int>("StaffExperienceId")
                        .HasColumnType("int");

                    b.Property<int>("StaffTypeId")
                        .HasColumnType("int");

                    b.Property<string>("TeacherId")
                        .HasColumnType("text");

                    b.Property<string>("Uannumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("WeddingDate")
                        .HasColumnType("datetime");

                    b.Property<string>("branchnumber")
                        .HasColumnType("text");

                    b.Property<string>("maritalStatus")
                        .HasColumnType("text");

                    b.HasKey("StaffId");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("SMS.Models.StaffAddress", b =>
                {
                    b.Property<int>("StaffAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("City")
                        .HasColumnType("int");

                    b.Property<int?>("Country")
                        .HasColumnType("int");

                    b.Property<string>("Line1")
                        .HasColumnType("text");

                    b.Property<string>("Line2")
                        .HasColumnType("text");

                    b.Property<string>("Line3")
                        .HasColumnType("text");

                    b.Property<string>("Pincode")
                        .HasColumnType("text");

                    b.Property<int?>("Sate")
                        .HasColumnType("int");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.HasKey("StaffAddressId");

                    b.HasIndex("StaffId");

                    b.ToTable("StaffAddress");
                });

            modelBuilder.Entity("SMS.Models.StaffAttachments", b =>
                {
                    b.Property<int>("StaffAttachmentsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DocumentType")
                        .HasColumnType("text");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("text");

                    b.Property<string>("PathToFile")
                        .HasColumnType("text");

                    b.HasKey("StaffAttachmentsId");

                    b.ToTable("StaffDocuments");
                });

            modelBuilder.Entity("SMS.Models.StaffExperience", b =>
                {
                    b.Property<int>("StaffExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("From")
                        .HasColumnType("datetime");

                    b.Property<string>("Responsibilty")
                        .HasColumnType("text");

                    b.Property<int?>("StaffId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("To")
                        .HasColumnType("datetime");

                    b.HasKey("StaffExperienceId");

                    b.HasIndex("StaffId");

                    b.ToTable("StaffExperience");
                });

            modelBuilder.Entity("SMS.Models.StaffFeedback", b =>
                {
                    b.Property<int>("StaffFeedbackID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AttachmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Empid")
                        .HasColumnType("text");

                    b.Property<string>("FeedbackType")
                        .HasColumnType("text");

                    b.Property<string>("Feedbacktitle")
                        .HasColumnType("text");

                    b.Property<string>("StaffName")
                        .HasColumnType("text");

                    b.Property<string>("TeacherId")
                        .HasColumnType("text");

                    b.HasKey("StaffFeedbackID");

                    b.ToTable("StaffFeedbacks");
                });

            modelBuilder.Entity("SMS.Models.StaffType", b =>
                {
                    b.Property<int>("StaffTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasKey("StaffTypeId");

                    b.ToTable("StaffTypes");

                    b.HasData(
                        new
                        {
                            StaffTypeId = 1,
                            Description = "Teacher"
                        },
                        new
                        {
                            StaffTypeId = 2,
                            Description = "Admin"
                        },
                        new
                        {
                            StaffTypeId = 3,
                            Description = "Principal"
                        },
                        new
                        {
                            StaffTypeId = 4,
                            Description = "Co-ordinator"
                        },
                        new
                        {
                            StaffTypeId = 5,
                            Description = "Support Staff"
                        },
                        new
                        {
                            StaffTypeId = 6,
                            Description = "Driver"
                        },
                        new
                        {
                            StaffTypeId = 7,
                            Description = "IT Technician"
                        },
                        new
                        {
                            StaffTypeId = 8,
                            Description = "Vice Principal"
                        },
                        new
                        {
                            StaffTypeId = 9,
                            Description = "Librarian"
                        },
                        new
                        {
                            StaffTypeId = 10,
                            Description = "Lab Staff"
                        },
                        new
                        {
                            StaffTypeId = 11,
                            Description = "PET"
                        },
                        new
                        {
                            StaffTypeId = 12,
                            Description = "HOD"
                        });
                });

            modelBuilder.Entity("SMS.Models.StaffeLetter", b =>
                {
                    b.Property<int>("StaffeLetterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AttachmentId")
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.Property<string>("Empid")
                        .HasColumnType("text");

                    b.Property<string>("LetterType")
                        .HasColumnType("text");

                    b.Property<string>("Month")
                        .HasColumnType("text");

                    b.Property<string>("StaffName")
                        .HasColumnType("text");

                    b.Property<string>("TeacherId")
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("StaffeLetterId");

                    b.ToTable("StaffeLetters");
                });

            modelBuilder.Entity("SMS.Models.State", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("stateDescr")
                        .HasColumnType("text");

                    b.HasKey("StateId");

                    b.ToTable("States");
                });

            modelBuilder.Entity("SMS.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("AadharNumber")
                        .HasColumnType("text");

                    b.Property<string>("AcademicPrecentage")
                        .HasColumnType("text");

                    b.Property<DateTime>("AdmissionDate")
                        .HasColumnType("datetime");

                    b.Property<int>("AdmissionNumber")
                        .HasColumnType("int");

                    b.Property<int?>("BloodGroup")
                        .HasColumnType("int");

                    b.Property<int?>("BusTripid")
                        .HasColumnType("int");

                    b.Property<string>("Class")
                        .HasColumnType("text");

                    b.Property<int>("DependentsId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime");

                    b.Property<string>("EmailId")
                        .HasColumnType("text");

                    b.Property<string>("EmisNumber")
                        .HasColumnType("text");

                    b.Property<int?>("FirstLanguage")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<long>("Mobile")
                        .HasColumnType("bigint");

                    b.Property<int?>("NationalityId")
                        .HasColumnType("int");

                    b.Property<string>("ReasonForLeaving")
                        .HasColumnType("text");

                    b.Property<int?>("ReligionId")
                        .HasColumnType("int");

                    b.Property<string>("RollNo")
                        .HasColumnType("text");

                    b.Property<int?>("Salutation")
                        .HasColumnType("int");

                    b.Property<int?>("SecondLanguage")
                        .HasColumnType("int");

                    b.Property<string>("Section")
                        .HasColumnType("text");

                    b.Property<int>("StudentAddressId")
                        .HasColumnType("int");

                    b.Property<int?>("passingOutSchool")
                        .HasColumnType("int");

                    b.Property<int?>("schoolBrand")
                        .HasColumnType("int");

                    b.Property<string>("schoolName")
                        .HasColumnType("text");

                    b.Property<int>("yearofattendence")
                        .HasColumnType("int");

                    b.HasKey("StudentId");

                    b.HasIndex("BusTripid");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("SMS.Models.StudentAddress", b =>
                {
                    b.Property<int>("StudentAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("City")
                        .HasColumnType("int");

                    b.Property<int?>("Country")
                        .HasColumnType("int");

                    b.Property<string>("Line1")
                        .HasColumnType("text");

                    b.Property<string>("Line2")
                        .HasColumnType("text");

                    b.Property<string>("Line3")
                        .HasColumnType("text");

                    b.Property<string>("Pincode")
                        .HasColumnType("text");

                    b.Property<int?>("Sate")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("StudentAddressId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentAddress");
                });

            modelBuilder.Entity("SMS.Models.StudentAttachments", b =>
                {
                    b.Property<int>("StudentAttachmentsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AdmissionNumber")
                        .HasColumnType("int");

                    b.Property<string>("DocumentType")
                        .HasColumnType("text");

                    b.Property<string>("PathToFile")
                        .HasColumnType("text");

                    b.HasKey("StudentAttachmentsId");

                    b.ToTable("StudentDocuments");
                });

            modelBuilder.Entity("SMS.Models.StudentFeedback", b =>
                {
                    b.Property<int>("StudentFeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AdmissionNumber")
                        .HasColumnType("int");

                    b.Property<int>("AttachmentId")
                        .HasColumnType("int");

                    b.Property<string>("Class")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FeedbackType")
                        .HasColumnType("text");

                    b.Property<string>("Feedbacktitle")
                        .HasColumnType("text");

                    b.Property<string>("Section")
                        .HasColumnType("text");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.HasKey("StudentFeedbackId");

                    b.ToTable("StudentFeedbacks");
                });

            modelBuilder.Entity("SMS.Models.TimeTable.ClassTimeTable", b =>
                {
                    b.Property<int>("ClassTimeTableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Class")
                        .HasColumnType("text");

                    b.Property<string>("Section")
                        .HasColumnType("text");

                    b.Property<DateTime>("Year")
                        .HasColumnType("datetime");

                    b.HasKey("ClassTimeTableId");

                    b.ToTable("ClassTimeTables");
                });

            modelBuilder.Entity("SMS.Models.TimeTable.PeriodDetail", b =>
                {
                    b.Property<int>("PeriodDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClassTimeTableId")
                        .HasColumnType("int");

                    b.Property<string>("Day")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.HasKey("PeriodDetailId");

                    b.HasIndex("ClassTimeTableId");

                    b.HasIndex("StaffId");

                    b.HasIndex("SubjectID");

                    b.ToTable("PeriodDetails");
                });

            modelBuilder.Entity("SMS.Models.Transport.BusTrip", b =>
                {
                    b.Property<int>("BusTripid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BusesAndDriverId")
                        .HasColumnType("int");

                    b.Property<int>("TotalHeadCount")
                        .HasColumnType("int");

                    b.Property<string>("TripAreas")
                        .HasColumnType("text");

                    b.Property<string>("TripNumber")
                        .HasColumnType("text");

                    b.Property<TimeSpan>("TripTimingFrom")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("TripTimingTo")
                        .HasColumnType("time");

                    b.HasKey("BusTripid");

                    b.HasIndex("BusesAndDriverId");

                    b.ToTable("BusTrips");
                });

            modelBuilder.Entity("SMS.Models.Transport.BusType", b =>
                {
                    b.Property<int>("BusTypeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BusTypeDesc")
                        .HasColumnType("text");

                    b.HasKey("BusTypeid");

                    b.ToTable("BusTypes");
                });

            modelBuilder.Entity("SMS.Models.Transport.BusesAndDriver", b =>
                {
                    b.Property<int>("BusesAndDriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BusNumber")
                        .HasColumnType("text");

                    b.Property<int>("BusTypeid")
                        .HasColumnType("int");

                    b.Property<string>("DriverAadhar")
                        .HasColumnType("text");

                    b.Property<string>("DriverName")
                        .HasColumnType("text");

                    b.Property<long>("DriverNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("InsuranceEndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("InsurancePolicyNum")
                        .HasColumnType("text");

                    b.Property<int>("NotificationSpanId")
                        .HasColumnType("int");

                    b.Property<int>("SeatCount")
                        .HasColumnType("int");

                    b.Property<string>("company")
                        .HasColumnType("text");

                    b.HasKey("BusesAndDriverId");

                    b.HasIndex("BusTypeid");

                    b.HasIndex("NotificationSpanId");

                    b.ToTable("BusesAndDrivers");
                });

            modelBuilder.Entity("SMS.Models.Transport.NotificationSpan", b =>
                {
                    b.Property<int>("NotificationSpanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NotificationSpanDesc")
                        .HasColumnType("text");

                    b.HasKey("NotificationSpanId");

                    b.ToTable("NotificationSpans");
                });

            modelBuilder.Entity("WebApi.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AcceptTerms")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PasswordReset")
                        .HasColumnType("datetime");

                    b.Property<string>("ResetToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("datetime");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime");

                    b.Property<string>("VerificationToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Verified")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("DependentsStudent", b =>
                {
                    b.HasOne("SMS.Models.Dependents", null)
                        .WithMany()
                        .HasForeignKey("DependentsdetailsDependentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMS.Models.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsStudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SMS.Models.Inventory.Inventory", b =>
                {
                    b.HasOne("SMS.Models.Inventory.InventoryItemType", "InventoryItemType")
                        .WithMany()
                        .HasForeignKey("InventoryItemTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMS.Models.Inventory.InventoryItemUsageArea", "InventoryItemUsageArea")
                        .WithMany()
                        .HasForeignKey("InventoryItemUsageAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItemType");

                    b.Navigation("InventoryItemUsageArea");
                });

            modelBuilder.Entity("SMS.Models.Leave.StaffLeave", b =>
                {
                    b.HasOne("SMS.Models.Staff", "Staffs")
                        .WithMany()
                        .HasForeignKey("StaffId");

                    b.Navigation("Staffs");
                });

            modelBuilder.Entity("SMS.Models.Leave.StudentLeave", b =>
                {
                    b.HasOne("SMS.Models.Student", "Students")
                        .WithMany()
                        .HasForeignKey("StudentId");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("SMS.Models.Message.Message", b =>
                {
                    b.HasOne("WebApi.Entities.Account", null)
                        .WithMany("Messages")
                        .HasForeignKey("AccountId");

                    b.HasOne("SMS.Models.Message.MessageRecipient", null)
                        .WithMany("Messages")
                        .HasForeignKey("MessageRecipientId");

                    b.HasOne("SMS.Models.Message.Message", "ParentMessage")
                        .WithMany()
                        .HasForeignKey("ParentMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMS.Models.Message.ReminderFrequency", null)
                        .WithMany("Messages")
                        .HasForeignKey("ReminderFrequencyId");

                    b.Navigation("ParentMessage");
                });

            modelBuilder.Entity("SMS.Models.Message.MessageRecipient", b =>
                {
                    b.HasOne("WebApi.Entities.Account", null)
                        .WithMany("MessageRecipients")
                        .HasForeignKey("AccountId");
                });

            modelBuilder.Entity("SMS.Models.StaffAddress", b =>
                {
                    b.HasOne("SMS.Models.Staff", null)
                        .WithMany("Addresses")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SMS.Models.StaffExperience", b =>
                {
                    b.HasOne("SMS.Models.Staff", null)
                        .WithMany("StaffExperiences")
                        .HasForeignKey("StaffId");
                });

            modelBuilder.Entity("SMS.Models.Student", b =>
                {
                    b.HasOne("SMS.Models.Transport.BusTrip", "StudentTrip")
                        .WithMany()
                        .HasForeignKey("BusTripid");

                    b.Navigation("StudentTrip");
                });

            modelBuilder.Entity("SMS.Models.StudentAddress", b =>
                {
                    b.HasOne("SMS.Models.Student", null)
                        .WithMany("Addresses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SMS.Models.TimeTable.PeriodDetail", b =>
                {
                    b.HasOne("SMS.Models.TimeTable.ClassTimeTable", "ClassTimeTable")
                        .WithMany("PeriodDetails")
                        .HasForeignKey("ClassTimeTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMS.Models.Staff", "Staffs")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMS.Models.Setup.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassTimeTable");

                    b.Navigation("Staffs");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SMS.Models.Transport.BusTrip", b =>
                {
                    b.HasOne("SMS.Models.Transport.BusesAndDriver", "BusesAndDrivers")
                        .WithMany()
                        .HasForeignKey("BusesAndDriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusesAndDrivers");
                });

            modelBuilder.Entity("SMS.Models.Transport.BusesAndDriver", b =>
                {
                    b.HasOne("SMS.Models.Transport.BusType", "BusType")
                        .WithMany()
                        .HasForeignKey("BusTypeid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMS.Models.Transport.NotificationSpan", "NotificationSpan")
                        .WithMany()
                        .HasForeignKey("NotificationSpanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusType");

                    b.Navigation("NotificationSpan");
                });

            modelBuilder.Entity("WebApi.Entities.Account", b =>
                {
                    b.OwnsMany("WebApi.Entities.RefreshToken", "RefreshTokens", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<int>("AccountId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("Created")
                                .HasColumnType("datetime");

                            b1.Property<string>("CreatedByIp")
                                .HasColumnType("text");

                            b1.Property<DateTime>("Expires")
                                .HasColumnType("datetime");

                            b1.Property<string>("ReplacedByToken")
                                .HasColumnType("text");

                            b1.Property<DateTime?>("Revoked")
                                .HasColumnType("datetime");

                            b1.Property<string>("RevokedByIp")
                                .HasColumnType("text");

                            b1.Property<string>("Token")
                                .HasColumnType("text");

                            b1.HasKey("Id");

                            b1.HasIndex("AccountId");

                            b1.ToTable("RefreshToken");

                            b1.WithOwner("Account")
                                .HasForeignKey("AccountId");

                            b1.Navigation("Account");
                        });

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("SMS.Models.Message.MessageRecipient", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("SMS.Models.Message.ReminderFrequency", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("SMS.Models.Staff", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("StaffExperiences");
                });

            modelBuilder.Entity("SMS.Models.Student", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("SMS.Models.TimeTable.ClassTimeTable", b =>
                {
                    b.Navigation("PeriodDetails");
                });

            modelBuilder.Entity("WebApi.Entities.Account", b =>
                {
                    b.Navigation("MessageRecipients");

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
