INSERT INTO [dbo].[Religions] ([ReligionName]) VALUES ('African Traditional & Diasporic')
INSERT INTO [dbo].[Religions] ([ReligionName]) VALUES ('Agnostic')
INSERT INTO [dbo].[Religions] ([ReligionName]) VALUES ('Atheist')
INSERT INTO [dbo].[Religions] ([ReligionName]) VALUES ('Baha''i')
INSERT INTO [dbo].[Religions] ([ReligionName]) VALUES ('Buddhism')
INSERT INTO [dbo].[Religions] ([ReligionName]) VALUES ('Cao Dai')
INSERT INTO [dbo].[Religions] ([ReligionName]) VALUES ('Chinese traditional religion')
INSERT INTO [dbo].[Religions] ([ReligionName]) VALUES ('Christianity')
INSERT INTO [dbo].[Religions] ([ReligionName]) VALUES ('Hinduism')
INSERT INTO [dbo].[Religions] ([ReligionName]) VALUES ('Islam')
INSERT INTO [dbo].[Religions] ([ReligionName]) VALUES ('Jainism')
INSERT INTO [dbo].[Religions] ([ReligionName]) VALUES ('Juche')
INSERT INTO [dbo].[Religions] ([ReligionName]) VALUES ('Judaism')
INSERT INTO [dbo].[Religions] ([ReligionName]) VALUES ('Neo-Paganism')
INSERT INTO [dbo].[Religions] ([ReligionName]) VALUES ('Non-religious')
INSERT INTO [dbo].[Religions] ([ReligionName]) VALUES ('Rastafarianism')
INSERT INTO [dbo].[Religions] ([ReligionName]) VALUES ('Secular')
INSERT INTO [dbo].[Religions] ([ReligionName]) VALUES ('Shinto')
INSERT INTO [dbo].[Religions] ([ReligionName]) VALUES ('Sikhism')
INSERT INTO [dbo].[Religions] ([ReligionName]) VALUES ('Spiritism')
INSERT INTO [dbo].[Religions] ([ReligionName]) VALUES ('Tenrikyo')
INSERT INTO [dbo].[Religions] ([ReligionName]) VALUES ('Unitarian-Universalism')
INSERT INTO [dbo].[Religions] ([ReligionName]) VALUES ('Zoroastrianism')
INSERT INTO [dbo].[Religions] ([ReligionName]) VALUES ('Primal-indigenous')
INSERT INTO [dbo].[Religions] ([ReligionName]) VALUES ('Other')